// 1
let a = 'hello';
let b = 'owu';
let c = 'com';
let d = 'ua';
let e = 1;
let f = 10;
let g = -999;
let h = 123;
let i = 3.14;
let j = 2.7;
let k = 16;
let l = true;
let m = false;
// console.log(a);
// // alert(a);
// document.write(`${a}<br>`);
// console.log(b);
// // alert(b);
// document.write(`${b}<br>`);
// console.log(c);
// // alert(c);
// document.write(`${c}<br>`);
// console.log(d);
// // alert(d);
// document.write(`${d}<br>`);
// console.log(e);
// // alert(e);
// document.write(`${e}<br>`);
// console.log(f);
// // alert(f);
// document.write(`${f}<br>`);
// console.log(g);
// // alert(g);
// document.write(`${g}<br>`);
// console.log(h);
// // alert(h);
// document.write(`${h}<br>`);
// console.log(i);
// // alert(i);
// document.write(`${i}<br>`);
// console.log(j);
// // alert(j);
// document.write(`${j}<br>`);
// console.log(k);
// // alert(k);
// document.write(`${k}<br>`);
// console.log(l);
// // alert(l);
// document.write(`${l}<br>`);
// console.log(m);
// //alert(m);
// document.write(`${m}<br>`);

// //2- переопределить каждую переменную из задания 1 дав им произвольные значения Вывести каждую при помощи console.log , alert, document.write
// a = -34;
// b = 0;
// c = 4;
// d = 'hello';
// e = true;
// f = 10;
// g = 'owu';
// h = 123;
// i = 3.14;
// j = false;
// k = 16;
// l = '';
// m = 'ua';
// console.log(a);
// // alert(a);
// document.write(`${a}<br>`);
// console.log(b);
// // alert(b);
// document.write(`${b}<br>`);
// console.log(c);
// // alert(c);
// document.write(`${c}<br>`);
// console.log(d);
// // alert(d);
// document.write(`${d}<br>`);
// console.log(e);
// // alert(e);
// document.write(`${e}<br>`);
// console.log(f);
// // alert(f);
// document.write(`${f}<br>`);
// console.log(g);
// // alert(g);
// document.write(`${g}<br>`);
// console.log(h);
// // alert(h);
// document.write(`${h}<br>`);
// console.log(i);
// // alert(i);
// document.write(`${i}<br>`);
// console.log(j);
// // alert(j);
// document.write(`${j}<br>`);
// console.log(k);
// // alert(k);
// document.write(`${k}<br>`);
// console.log(l);
// // alert(l);
// document.write(`${l}<br>`);
// console.log(m);
// //alert(m);
// document.write(`${m}<br>`);

//3- Создать 3 числовых и 3 стринговых константы. Вывести каждую при помощи console.log , alert, document.write
// const val_N1 = 23;
// const val_N2 = 4343;
// const val_N3 = 1;

// const val_S1 = 'wwww';
// const val_S2 = 'dddd';
// const val_S3 = 'rrrrr';
// console.log(val_N1);
// console.log(val_N2);
// console.log(val_N3);

// console.log(val_S1);
// console.log(val_S2);
// console.log(val_S3);
//4- при помощи 3х разных prompt() получить 3 слова которые являются вашими ФИО. Для фамилии имени и отчества создать разные переменные. Вывести каждую при помощи console.log , alert, document.write
let surname = prompt('Enter your surname');
let username = prompt('Enter your name');
let patronymic = prompt('Enter your patronymic');

console.log(surname);
document.write(`${surname}<br>`);
console.log(username);
document.write(`${username}<br>`);
console.log(patronymic);
document.write(`${patronymic}<br>`);
//-5- Взять переменные из задания 4 и сконкатенировать их в одной переменной person.

let person = surname +" "+ username +" "+ patronymic;
console.log(person);